#!/usr/bin/env python3
import i3ipc, os, subprocess
 
i3 = i3ipc.Connection()

def get_config(name, class_, resource, default=""):
    path = name, class_, resource
    xresource = '.'.join(path)
    env = "_".join(path).upper()
    
    try:
        return os.environ[env]
    except KeyError:
        return subprocess.check_output(
            ['xrescat', xresource, default]
        ).decode()
        
split_v_text = get_config('i3xrocks', 'layout', 'verticalIcon', '')
split_h_text = get_config('i3xrocks', 'layout', 'horizontalIcon', '')
split_none_text = get_config('i3xrocks', 'layout', 'noneIcon', '')
label_icon = get_config('i3xrocks', 'layout', 'blockIcon', '')

value_colour = get_config('i3xrocks', 'value', 'color', "#D8DEE9")
label_colour = get_config('i3xrocks', 'label', 'color', "#7B8394")
value_font = get_config('i3xrocks', 'value', 'font', "Source Code Pro Medium 13")


layout_text_map = {
    'splitv': split_v_text,
    'splith': split_h_text    
}


def update_display(layout=None):
    layout_text = layout_text_map.get(layout, split_none_text)
    print(f'<span color="{label_colour}">{label_icon}</span><span font_desc="{value_font}" color="{value_colour}"> {layout_text}</span>', flush=True)

 
def on_event(self, _):
    parent = i3.get_tree().find_focused().parent
    update_display(parent.layout)
 
 
# Subscribe to events
i3.on("window::focus", on_event)
i3.on("binding", on_event)

update_display()

# Start the main loop and wait for events to come in.
i3.main()
